version: '3'

services:
  registry:
    image: registry:latest
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # オプション
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - registry:/var/lib/registry
      - ./auth:/auth
      # オプション
      - ./certs:/certs
    ports:
      - 5000:5000

  web:
    depends_on:
      - registry
    image: parabuzzle/craneoperator:latest
    ports:
      - 8080:80
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PROTOCOL=https
      - SSL_VERIFY=false
      - REGISTRY_PUBLIC_URL=localhost
      - ALLOW_REGISTRY_LOGIN=true
      - REGISTRY_ALLOW_DELETE=true
      # ベーシック認証用のID/PW
      # - USERNAME=username
      # - PASSWORD=password

volumes:
  registry:
